import { IConsumer } from '@models/consumer';

export const dummyConsumers: IConsumer[] = [
  {
    id: 1,
    firstName: 'Mei',
    lastName: 'Khor',
    email: 'mei.khor@jp.ey.com',
    badge: 'gold',
    greenPoints: 1000,
    address: '123 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-999-9999',
    avatar: 'avatar-mei',
  },
  {
    id: 2,
    firstName: 'Don',
    lastName: 'Gomez',
    email: 'don.reinard.gomez@jp.ey.com',
    badge: 'bronze',
    greenPoints: 250,
    address: '456 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-888-8888',
    avatar: 'avatar-don',
  },
  {
    id: 3,
    firstName: 'Kazuyuki',
    lastName: 'Suto',
    email: 'kazuyuki.suto@jp.ey.com',
    badge: 'platinum',
    greenPoints: 50000,
    address: '789 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-777-7777',
    avatar: 'avatar-suto',
  },
  {
    id: 4,
    firstName: 'Joe',
    lastName: 'Ashizawa',
    email: 'joe.ashizawa@jp.ey.com',
    badge: 'silver',
    greenPoints: 500,
    address: '101 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-666-6666',
    avatar: 'avatar-joe',
  },
  {
    id: 5,
    firstName: 'Min',
    lastName: 'Luo',
    email: 'min.luo@jp.ey.com',
    badge: 'none',
    greenPoints: 0,
    address: '532 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-555-5555',
    avatar: 'avatar-min',
  },
  {
    id: 6,
    firstName: 'Ryota',
    lastName: 'Nakayama',
    email: 'ryota.nakayama@jp.ey.com',
    badge: 'bronze',
    greenPoints: 200,
    address: '3453 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-444-4444',
    avatar: 'avatar-nakayama',
  },
];
