import { IStaff } from '@models/staff';

export const dummyStaffs: IStaff[] = [
  {
    id: 1,
    firstName: 'Mei',
    lastName: 'Khor',
    email: 'mei.khor@jp.ey.com',
    address: '123 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-999-9999',
    avatar: 'avatar-mei',
    moodRating: 'happy',
  },
  {
    id: 2,
    firstName: 'Don',
    lastName: 'Gomez',
    email: 'don.reinard.gomez@jp.ey.com',
    address: '456 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-888-8888',
    avatar: 'avatar-don',
    moodRating: 'sad',
  },
  {
    id: 3,
    firstName: 'Kazuyuki',
    lastName: 'Suto',
    email: 'kazuyuki.suto@jp.ey.com',
    address: '789 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-777-7777',
    avatar: 'avatar-suto',
    moodRating: 'angry',
  },
  {
    id: 4,
    firstName: 'Joe',
    lastName: 'Ashizawa',
    email: 'joe.ashizawa@jp.ey.com',
    address: '101 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-666-6666',
    avatar: 'avatar-joe',
    moodRating: 'normal',
  },
  {
    id: 5,
    firstName: 'Min',
    lastName: 'Luo',
    email: 'min.luo@jp.ey.com',
    address: '532 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-555-5555',
    avatar: 'avatar-min',
    moodRating: 'stressed',
  },
  {
    id: 6,
    firstName: 'Ryota',
    lastName: 'Nakayama',
    email: 'ryota.nakayama@jp.ey.com',
    address: '3453 Fake Streen, Fake Road, Fake City',
    phoneNmber: '+81-80-444-4444',
    avatar: 'avatar-nakayama',
    moodRating: 'stressed',
  },
];
